[General]
ipv6 = false
bypass-system = true
dns-server = https://dns.alidns.com/dns-query, https://doh.pub/dns-query
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.18.0.0/15, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32

[Proxy Group]
模式选择 = select,智能优选, 流量节省, 手动选择, 电信优化, 联通优化, 移动优化
手动选择= select, policy-regex-filter=^(.(?!(VPN|BUD)))*$
智能优选 = url-test,policy-regex-filter=^(.(?!(VPN|BUD)))*$ ,interval=600,tolerance=0,timeout=5,url=http://www.gstatic.com/generate_204
流量节省 = url-test,policy-regex-filter=(?=.*1.0x)^.* ,interval=600,tolerance=100,timeout=5,url=http://www.gstatic.com/generate_204
电信优化 = url-test,policy-regex-filter=(?=.*(BGP|TEL))^.* ,interval=600,tolerance=100,timeout=5,url=http://www.gstatic.com/generate_204
联通优化 = url-test,policy-regex-filter=(?=.*(BGP|UNI))^.* ,interval=600,tolerance=100,timeout=5,url=http://www.gstatic.com/generate_204
移动优化 = url-test,policy-regex-filter=(?=.*(BGP|MOB))^.* ,interval=600,tolerance=100,timeout=5,url=http://www.gstatic.com/generate_204
vpn-out  = url-test,policy-regex-filter=(?=.*VPN)^.*,interval=86400,tolerance=0, timeout=5,url=http://www.gstatic.com/generate_204
download-out = url-test,policy-regex-filter=(?=.*BUD)^.*,interval=600,tolerance=100,timeout=5,url=http://www.gstatic.com/generate_204

[Rule]
RULE-SET,https://raw.githubusercontent.com/Cats-Team/AdRules/main/adrules.list, REJECT
RULE-SET,https://raw.githubusercontent.com/znt0948/proxy-ruleset-manager/refs/heads/main/rule/shadowrocket/geosite-category-download@!cn.list,download-out
RULE-SET,https://raw.githubusercontent.com/znt0948/proxy-ruleset-manager/refs/heads/main/rule/shadowrocket/geoip-category-download@!cn.list,download-out
RULE-SET,https://raw.githubusercontent.com/znt0948/proxy-ruleset-manager/refs/heads/main/rule/shadowrocket/geosite-category-vpn@!cn.list,vpn-out
RULE-SET,https://raw.githubusercontent.com/znt0948/proxy-ruleset-manager/refs/heads/main/rule/shadowrocket/geosite-category-direct.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/znt0948/proxy-ruleset-manager/refs/heads/main/rule/shadowrocket/geoip-category-direct.list,DIRECT
FINAL,模式选择
